factory_settings = {
    "firmwareAtShipment"  : "v2.0",
    "productName"         : "RAS2.1",
    "productionDate"      : "to be defined",
    "productionLocation"  : "Frankfurt",
    "productionNumber"    : "01",
    "qualityInspector"    : "Luis", 
    "SSIDreset"           : "__RAS__",
    "hashed_machine_id"   : "to be defined",
    "setup_password"      : "mq5RMj",
    "ordered_by"          : "to be defined",
    "invoice_nr"          : "to be defined",
    "RAS_hostname"        : "01",
    "tz"                  : "Europe/Berlin",
    "hardware_machine"    : "RPi Zero W",
    "hardware_card_reader": "MFRC522",
    "hardware_display"    : "oled sh1106",
    "hardware_sound"      : "passive buzzer",
    "time_format"         : "12 hour",
}
